package:
  format-version: "1.0.0"
  name: "core"
  type: "api"
  status: "production"
  required: false
  version: "dev"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "dev"
    - name: "csp"
      type: "package"
      version: "dev"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "littlefs"
      type: "package"
      version: "v2.5.0"
    - name: "filex"
      type: "package"
      version: "v6.2.0_rel"