package:
  format-version: "1.0.0"
  name: "core"
  type: "api"
  status: "production"
  required: false
  version: "v3.13.2"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "csp"
      type: "package"
      version: "v3.18.2"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "littlefs"
      type: "package"
      version: "v2.5.1"
    - name: "filex"
      type: "package"
      version: "v6.2.1_rel"