package:
  format-version: "1.0.0"
  name: "core"
  type: "api"
  status: "production"
  required: false
  version: "3.12.0"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "3.15.0"
    - name: "csp"
      type: "package"
      version: "3.16.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.4.6"
    - name: "littlefs"
      type: "package"
      version: "2.5.0"
    - name: "filex"
      type: "package"
      version: "6.2.0_rel"