package:
  format-version: "1.0.0"
  name: "core"
  type: "api"
  status: "production"
  required: false
  version: "v3.13.4"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.18.0"
    - name: "csp"
      type: "package"
      version: "v3.18.5"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"